name: Update Leaderboard

on:
  schedule:
    - cron: '0 */3 * * *'   # Run every 3 hours
  workflow_dispatch:         # Allow manual trigger

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and dependencies
        run: |
          playwright install chromium
          playwright install-deps chromium

      - name: Create config directory
        run: mkdir -p config

      - name: Create .env file from secrets
        run: |
          cat > config/.env <<EOF
DRIVE_XLSX_LINK=${{ secrets.DRIVE_XLSX_LINK }}
SUPABASE_URL=${{ secrets.SUPABASE_URL }}
SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}
DATA_DIR=./data
REQUESTS_TIMEOUT=15
SLEEP_SECONDS=2
USE_PLAYWRIGHT_FALLBACK=true
EOF

      - name: Run scraper
        env:
          DRIVE_XLSX_LINK: ${{ secrets.DRIVE_XLSX_LINK }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard-data
          path: |
            data/*.csv
            data/*.json
          retention-days: 30

      - name: Commit and push updated data (optional)
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/*.csv data/*.json || true
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update leaderboard data [skip ci]" && git push)
        continue-on-error: true
